openapi: 3.0.1
info:
  title: temp_storage
  description: API-documentation for temp_storage
  license:
    name: MIT
    url: https://raw.githubusercontent.com/Traperto/temp_storage/master/LICENSE
  version: 0.6.2
servers:
- url: http://localhost:8080/
security:
- bearerAuth: []
tags:
- name: Records
  description: ""
paths:
  /all:
    get:
      tags:
      - Records
      summary: Gets all stored records
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    temperature:
                      type: number
                      example: 23.3
                    humidity:
                      type: number
                      example: 42.1
                    timestamp:
                      type: string
                      example: 2018-05-04T23:24:15.000Z
        401:
          description: Unauthorized
          content: {}
        500:
          description: Internal Server Error
          content: {}
  /average:
    get:
      tags:
      - Records
      summary: Gets average temperature and humidity
      responses:
        200:
          description: successful operation
          content:
            '*/*':
              schema:
                type: object
                properties:
                  temperature:
                    type: number
                    example: 23.3
                  humidity:
                    type: number
                    example: 42.1
        401:
          description: Unauthorized
          content: {}
        500:
          description: Internal Server Error
          content: {}
  /create:
    post:
      tags:
      - Records
      summary: Creates a new record
      requestBody:
        description: Object containing the record-data
        content:
          application/json:
            schema:
              type: object
              properties:
                temperature:
                  type: number
                  example: 23.4
                humidity:
                  type: number
                  example: 44.5
                timetamp:
                  type: string
                  description: If not set, it will set current timestamp
                  example: 2018-05-04T23:24:15.000Z
        required: true
      responses:
        201:
          description: Created
          content: {}
        400:
          description: Bad Request due to invalid data
          content: {}
        401:
          description: Unauthorized
          content: {}
        500:
          description: Internal Server Error
          content: {}
      x-codegen-request-body-name: body
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT